### ISSUE TITLE
Could write .gb/gbc file back to card cartridge ?

### ISSUE THREAD

**Issue by aloveric** [drhelius/arduinogameboy#1]
Very cool project which using Mega to deal with Gameboy cartridge. 
So could it write .gb/gbc file back to card cartridge?
Actually, I found some one made a read/write product using Mega8515 chip to do these things.
Waiting for your feedback.

**Comment by drhelius** [comment]
If you are referring to writing ROMs in cartridges, no, this project is for reading ROM and reading/writing RAM with original cartridges.

You could of course modify it to write into your own custom cartridges too.
